api:
  id: ""
  path: "/api/*"

http:
  host: "0.0.0.0"
  port: "8081"
  secure-port: "8082"
  private:
    port: "8091"
    secure-port: "8092"

salesforce:
  username: "TBD"

cosmosdb:
  db-account-url: "TBD"
  version: "TBD"

circuit-breaker:
  threshold: "0.5"
  scheduler:
    frequency: "60000"
  os:
    max-entries: "1"
    entry-ttl: "86400"
    expiration-interval: "1"
